### ISSUE TITLE
Création d'un stage

### ISSUE THREAD

**Issue by JeanPhilippeL** [csf-dept-info/stagio#10]
Certains champs de vérification ne sont pas vérifié.
http://i.gyazo.com/d1322d10fb03652be9ef92d8cce0fd10.png

**Comment by marcantoinefortier** [comment]
Comme mentionné ici https://github.com/csf-dept-info/stagio/issues/14

Aucune validation n'est effectuée puisque ces informations sont laissées à la discretion de l'employé. Le coordonnateur peut toujours refuser la publication d'une offre de stage s'il juge les informations non pertinentes.
