### ISSUE TITLE
Mot de Passe

### ISSUE THREAD

**Issue by MonsieurRoss** [csf-dept-info/stagio#11]
Je change mon mot de passe pour le même mot de passe que j'ai présentement et cela fonctionne

**Comment by maferland** [comment]
Ce n'est pas un bogue.

**Comment by marcantoinefortier** [comment]
Cette vérification nous ne semblait pas essentielle dans le développement de l'application. Nous ne croyons pas qu'il s'agit de bogue étant donné que l'utilisateur peut bien changer son mot de passe par le même s'il en a envie.

Merci pour votre remarque.
